# Generated by Django 3.2.12 on 2024-02-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('team_points', models.CharField(max_length=10)),
                ('team_position', models.CharField(max_length=10)),
            ],
        ),
    ]
